// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyu-QiTjaKeGFP1wDtKAiHY63d7GEUqes',
    appId: '1:418496117056:web:211b93c499cb3f84ab62a5',
    messagingSenderId: '418496117056',
    projectId: 'app-motos-afb0d',
    authDomain: 'app-motos-afb0d.firebaseapp.com',
    storageBucket: 'app-motos-afb0d.firebasestorage.app',
    measurementId: 'G-HKQCY47NXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGT6PLAqLhnt-nhqYEpfqZ4mNyClMbfcg',
    appId: '1:418496117056:android:dfc7abafd7415bf6ab62a5',
    messagingSenderId: '418496117056',
    projectId: 'app-motos-afb0d',
    storageBucket: 'app-motos-afb0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtYDEIdAq5ezIcFL8J79WAHJsY4EzrVwg',
    appId: '1:418496117056:ios:fa17d3e0ec937cb5ab62a5',
    messagingSenderId: '418496117056',
    projectId: 'app-motos-afb0d',
    storageBucket: 'app-motos-afb0d.firebasestorage.app',
    iosBundleId: 'com.example.appMotos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtYDEIdAq5ezIcFL8J79WAHJsY4EzrVwg',
    appId: '1:418496117056:ios:fa17d3e0ec937cb5ab62a5',
    messagingSenderId: '418496117056',
    projectId: 'app-motos-afb0d',
    storageBucket: 'app-motos-afb0d.firebasestorage.app',
    iosBundleId: 'com.example.appMotos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyu-QiTjaKeGFP1wDtKAiHY63d7GEUqes',
    appId: '1:418496117056:web:07fdb0036cb5cfd1ab62a5',
    messagingSenderId: '418496117056',
    projectId: 'app-motos-afb0d',
    authDomain: 'app-motos-afb0d.firebaseapp.com',
    storageBucket: 'app-motos-afb0d.firebasestorage.app',
    measurementId: 'G-03KKMWCJJX',
  );
}
